### ISSUE TITLE
Brew formula using deprecated mechanism

### ISSUE THREAD

**Issue by bmihaila** [pirj/homebrew-noclamshell#3]
Recently this warning pops up when using homebrew:

```
Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the pirj/noclamshell tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/pirj/homebrew-noclamshell/Formula/noclamshell.rb:11
```

The annoying part is that homebrew displays that warning on any install of any package, not only when handling noclamshell.
Is it possible to update the formula to fix the warning?

Thanks
Bogdan

**Comment by pirj** [comment]
Thanks for reporting, this is already being worked on in #2

**Comment by bmihaila** [comment]
Oh great. Should have refreshed the browser as last time I looked there was no such thing. Thanks a lot for your work! Your tool fills a dire gap in usability.
